default_config:

homeassistant:
  packages: !include_dir_named packages/

tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

lovelace: !include lovelace.yaml

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - http://localhost:4000/mushroom.js
#   development_repo: /workspaces/home-assistant-frontend


input_number:
  comfort:
    name: "Comfort"
    icon: mdi:heating-coil
    min: 5
    max: 45
    step: 1
    initial: 22
    unit_of_measurement: "°C"
    mode: slider
  eco:
    name: "Eco"
    icon: mdi:heating-coil
    min: 5
    max: 45
    step: 1
    initial: 22
    unit_of_measurement: "°C"
    mode: slider
